### PR TITLE
Add Release Workflow

### PR DESCRIPTION
**Pull request by roehrich-hpe**
Each build will get one or more image tags, depending on whether it's a build of the master branch, a PR branch, or a release branch.  Computation of the image tags is handled by the metadata-action workflow.

* Add git-version-gen script to compute a VERSION value from the git repo.
* Remove the .version file; this is now computed by the git-version-gen script.
* Add rules to Makefile to generate the .version file and use its value.
* Use "v" prefix in release tag filter.
* Add workflow to verify that tags are annotated.
* Use metadata-action to generate all of the appropriate tags for the build
* Use build-push-action to execute all of the tags for the build.

Tagging:
* Builds of the master branch get an image tag of "master".
* Builds of a PR branch get an image tag similar to "pr-3".
* Builds of a PR or merge event get an image tag similar to "0.0.1.12-9e04", which is the value generated by git-version-gen.
* Builds of a PR or merge event will get an image tag that is the long SHA of the top commit, which is the image tag expected by nnf-deploy.
* Builds of a push to a tag will get an image tag that matches the git tag.
* Builds of a push to a tag will get an image tag of "latest".

### CODE REVIEW

**Comment by roehrich-hpe** [comment]
This is copied from DWS.

**Review by bdevcich — APPROVED** [review]

**Comment by bdevcich** [comment]
Do we need to hold on off merging this until I get #8 merged?

**Comment by roehrich-hpe** [comment]
> Do we need to hold on off merging this until I get #8 merged?

I don't see any technical reason to order them in any particular way, unless you have something in mind.

**Review by matthew-richerson — APPROVED** [review]

**Comment by bdevcich** [comment]
I was thinking this would cut a 0.0.1 version, but that's not the case, right?

**Comment by roehrich-hpe** [comment]
> I was thinking this would cut a 0.0.1 version, but that's not the case, right?

I have a few more steps to get there, after this merges.

**Pull request merged**
